spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  messages:
    basename: messages
  security:
    user:
      name: crud
      password: crud

management:
  endpoints:
    web:
      exposure:
        include: '*'
